### ISSUE TITLE
GrovePi.Analog.write/2 results in error

### ISSUE THREAD

**Issue by axelclark** [fhunleth/grovepi#18]
I am trying to implement this project:  https://github.com/DexterInd/GrovePi/blob/master/Projects/LED_Fade/led_fade.py

```py
# Connect the LED to digital port D5
led = 5
grovepi.pinMode(led,"OUTPUT")

# Where i is the output of the potentiometer.
grovepi.analogWrite(led,i//4)
```
I'm just trying to get the led to work by itself.  I have an led board connected to port D5.

Looking at the GrovePi.Analog docs, I should just be able to call:
```
GrovePi.Analog.write(5, 200)
```

However, I get this error:
```
fe423e:        00:04:53.474 [error] GenServer Default.Elixir.GrovePi.Board terminating
** (MatchError) no match of right hand side value: :error
    (elixir_ale) lib/elixir_ale/i2c.ex:171: ElixirALE.I2C.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:write, <<4, 5, 200, 0>>}
State: %ElixirALE.I2C.State{address: 4, devname: "i2c-1", port: #Port<0.971>}
fe423e:        00:04:54.052 [error] GenServer {Default.Elixir.GrovePi.Registry.Pin, 14} terminating
** (stop) exited in: GenServer.call(Default.Elixir.GrovePi.Board, {:write, <<1, 14, 0, 0>>}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :error
            (elixir_ale) lib/elixir_ale/i2c.ex:171: ElixirALE.I2C.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (grovepi) lib/grovepi/board.ex:80: GrovePi.Board.send_request_with_retry/3
    (grovepi) lib/grovepi/digital.ex:34: GrovePi.Digital.read/2
    (grovepi) lib/grovepi/poller.ex:135: GrovePi.Button.update_value/1
    (grovepi) lib/grovepi/poller.ex:128: GrovePi.Button.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :poll_button
State: %GrovePi.Button.State{pin: 14, poll_interval: 100, poll_reference: #Reference<0.0.1.2292>, prefix: Default, trigger: GrovePi.Button.DefaultTrigger, trigger_state: %GrovePi.Button.DefaultTrigger.State{value: 0}}
```

Do I need to do something else before the GrovePi.Analog.write/2 function call?  Do I need to set the pin mode?  Or am I doing something else wrong?

**Comment by fhunleth** [comment]
Could you share your program or reproduce the issue in iex and share the steps again? The text above doesn't look quite right. For example, `pinMode` and `:poll_button` make me think that something might have been lost in the copy/paste. (or maybe not, but please confirm)

Also, Port D5 is an I2C port, so could you attach the LED to Port D3? Port D3 is a PWM-capable digital port. Oddly enough, it looks like the only easy PWM output to use. I'm not sure how port D5 could be made to work, but I haven't looked at the schematic. The GrovePi+ docs look misleading on that one.

**Comment by axelclark** [comment]
I no longer have the error, although I'm not sure what was causing it.  Today I started with a new project and I actually could get it working on both Port D3 and Port D5.  

I went back to my project and got the same error as above.  I commented out all of my button and led code and then did not have the error.  Then when I uncommented the code, I also no longer had the error.  I have it working on both Port D3 and D5.  So I'm not sure what the issue was but everything is working now.

Here is my code:

lib/demo/application.ex
```elixir
defmodule Demo.Application do
  use Application

  @interface :wlan0

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    # Define workers and child supervisors to be supervised
    children = [
      # worker(Demo.Worker, [arg1, arg2, arg3]),
      worker(Task, [fn -> init_kernel_modules() end],
        restart: :transient, id: Nerves.Init.KernelModules),
      worker(Task, [fn -> init_wifi_network() end],
        restart: :transient, id: Nerves.Init.WifiNetwork),
      worker(NetworkManager, [@interface],
        restart: :transient, id: Nerves.Init.NetworkManager),
      supervisor(HelloGrove.Supervisor, []),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Demo.Supervisor]
    Supervisor.start_link(children, opts)
  end

  def init_kernel_modules, do: System.cmd "modprobe", ["brcmfmac"]

  def init_wifi_network() do
    Nerves.InterimWiFi.setup @interface, Application.get_env(:demo, @interface)
  end
end
```

lib/hello_grove/supervisor.ex
```elixir
defmodule HelloGrove.Supervisor do
  use Supervisor

  # Pick ports that work on both the GrovePi+ and GrovePi Zero
  @button_pin 14 # Port A0
  # @buzzer_pin 3 # Port D3
  @led_pin 3

  def start_link() do
    IO.puts "Starting HelloGrove.Supervisor"

    Supervisor.start_link(__MODULE__, nil)
  end

  def init(_) do
      # Define workers and child supervisors to be supervised
    children = [
      # Start the GrovePi sensors that we want
      worker(GrovePi.Button, [@button_pin]),
      # worker(GrovePi.Buzzer, [@buzzer_pin]),

      # Start the main app
      worker(HelloGrove, [[@button_pin, @led_pin]]),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: HelloGrove.Supervisor]
    supervise(children, opts)
  end
end
```

lib/hello_grove.ex
```elixir
defmodule HelloGrove do
  @moduledoc false
  use GenServer

  defstruct [:button, :led]

  def start_link(pins) do
    GenServer.start_link(__MODULE__, pins)
  end

  def init([button, led]) do
    state = %HelloGrove{button: button, led: led}

    GrovePi.Button.subscribe(state.button, :pressed)
    {:ok, state}
  end

  def handle_info({_, :pressed, _}, state) do
    IO.puts("Alert!!!!")

    # Sound the alarm, but only for a second
    # GrovePi.Buzzer.buzz(state.buzzer, 1000)
    GrovePi.Analog.write(state.led, 125)

    {:noreply, state}
  end
end
```

**Comment by axelclark** [comment]
I still seem to occasionally get this error.  I think my first post was missing some in the copy/paste as you suggested. EDIT:  Looking at it again, I think I did get all of the error message in my first post.

With the code the same as above.  I have a potentiometer in Port A2.  In iex I called:

```elixir
iex(demo@192.168.0.100)6> GrovePi.Analog.read(16)
```

The first time I got the error below (copied from cell watch).

```elixir
fe423e:        00:22:35.498 [error] GenServer Default.Elixir.GrovePi.Board terminating
** (MatchError) no match of right hand side value: :error
    (elixir_ale) lib/elixir_ale/i2c.ex:167: ElixirALE.I2C.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:read, 1}
State: %ElixirALE.I2C.State{address: 4, devname: "i2c-1", port: #Port<0.971>}
fe423e:        00:22:36.026 [error] GenServer {Default.Elixir.GrovePi.Registry.Pin, 14} terminating
** (stop) exited in: GenServer.call(Default.Elixir.GrovePi.Board, {:read, 1}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: :error
            (elixir_ale) lib/elixir_ale/i2c.ex:167: ElixirALE.I2C.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (grovepi) lib/grovepi/board.ex:88: GrovePi.Board.get_response_with_retry/3
    (grovepi) lib/grovepi/digital.ex:35: GrovePi.Digital.read/2
    (grovepi) lib/grovepi/poller.ex:135: GrovePi.Button.update_value/1
    (grovepi) lib/grovepi/poller.ex:128: GrovePi.Button.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :poll_button
State: %GrovePi.Button.State{pin: 14, poll_interval: 100, poll_reference: #Reference<0.0.1.2283>, prefix: Default, trigger: GrovePi.Button.DefaultTrigger, trigger_state: %GrovePi.Button.DefaultTrigger.State{value: 0}}
```

The second time I got
```elixir
iex(demo@192.168.0.100)6> GrovePi.Analog.read(16)
508
```
I continue to intermittently get this error when I read the sensor.

**Comment by axelclark** [comment]
Ok, I just realized what may have been happening with the original error.  I had a bad LED light which was why the LED wasn't working.  At the same time, I was getting the error when I was trying to write to the pin for the LED.  I don't think the error was causing the light not to work, but I do think writing to the LED pin was causing the error.  Although now I can't reproduce it with the LED in Port D5 or D3 (only with the potentiometer in Port A2), so again I'm not sure.
